#spring.datasource.url= jdbc:mysql://todo-db.crgyiukce4t8.ap-northeast-2.rds.amazonaws.com/todolist
#spring.datasource.username=admin
#spring.datasource.password=1q2w3e4r!
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring:
  datasource:
    url: jdbc:mysql://dogreen-db.chg6o0y6ulw5.ap-northeast-2.rds.amazonaws.com/todolist
    username: admin
    password: dlwoqls123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
